# Generated by Django 5.1.1 on 2026-03-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.TextField()),
                ('user_email', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
