# Generated by Django 5.1.1 on 2026-03-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.TextField(max_length=4)),
                ('product_id', models.TextField(max_length=5)),
                ('category', models.TextField(max_length=20)),
                ('region', models.TextField(max_length=5)),
                ('inventory_level', models.IntegerField()),
                ('units_sold', models.IntegerField()),
                ('units_ordered', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('weather_condition', models.TextField()),
                ('promotion', models.IntegerField()),
                ('competitor_pricing', models.FloatField()),
                ('seasonality', models.TextField()),
                ('epidemic', models.IntegerField()),
                ('demand', models.IntegerField()),
            ],
            options={
                'db_table': 'sales_data',
            },
        ),
    ]
