# Generated by Django 5.1.1 on 2026-03-25 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_app', '0002_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='products_list',
            fields=[
                ('products_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.TextField(max_length=5)),
                ('product_description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'products_list',
            },
        ),
        migrations.AlterField(
            model_name='sales',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, to='hackathon_app.sales'),
        ),
    ]
