# Generated by Django 5.1.1 on 2026-03-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_app', '0003_products_list_alter_sales_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product_id',
            field=models.TextField(max_length=5),
        ),
    ]
