# Generated by Django 5.1.1 on 2026-03-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_app', '0004_alter_sales_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products_list',
            old_name='product_id',
            new_name='product_label',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='product_id',
            new_name='product_label',
        ),
    ]
